on:
  push:
    branches:
      - main
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: First time
        run: echo "Job Started"
      - name: Git Checkout
        run: git clone https://github.com/vinodraajalingam/PersonalAI-FastAPI.git
      - name: Clone Status
        run: echo "Git Clone Completed"
      - name: Install Python
        run: sudo install python -y
      - name: Install Pip
        run: sudo install pip -y
      - name: Python, Pip Status
        run: echo "Python,Pip Installed"
      - name: List files
        run: ls -lrt
