on:
  push:
    branches:
      - main
jobs:
  deploy_fastapi:
    runs-on: self-hosted
    steps:
      - name: Git Checkout
        run: git clone https://github.com/vinodraajalingam/PersonalAI-FastAPI.git
      - name: Update Apt
        run: sudo apt update
      - name: Install Python
        run: sudo apt install python3 -y
      - name: Install Pip
        run: sudo apt install python3-pip -y
      - name: Install Dependency
        run: |
              cd PersonalAI-FastAPI
              sudo apt install python3-venv python3-full -y
              python3 -m venv venv
              source venv/bin/activate
              echo "req install begin.."
              pip3 install -r requirement.txt
              hostname -I
              echo "req install end.."
              uvicorn main:app --reload --host 0.0.0.0 --port 9000 &
              sleep 80
