on:
  push:
    branches:
      - main
jobs:
  deploy_fastapi:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        run: git clone https://github.com/vinodraajalingam/PersonalAI-FastAPI.git
      - name: Update Apt
        run: sudo apt update
      - name: Install Python
        run: sudo apt install python3 -y
      - name: Install Pip
        run: sudo apt install python3-pip -y
      - name: Install Dependency
        run: |
              cd PersonalAI-FastAPI
              pip3 install -r requirement.txt
              hostname -I
              uvicorn main:app --reload --port 9000 &
              sleep 50
